[package]
    name = 'verifier'
    version = '0.1.0'
    edition = '2021'
    authors = [ 'ENDERZOMBI102 <enderzombi102.end@gmail.com>' ]

[dependencies]
    clap = { version = '4.3.19', features = [ 'env' ] }
    crc32fast = '1.3.2'
    sha2 = '0.10.7'
    glob = '0.3.1'
    glob-match = '0.2.1'